version: '3.4'

x-neuron-service: &neuron-service
    image: neuron
    build:
        context: .
        dockerfile: Dockerfile
    restart: on-failure
    volumes:
        - raw:/app/raw
        - data:/app/data

services:
    rabbit:
        image: rabbitmq:alpine
    mongo:
        image: mongo

    server:
        <<: *neuron-service
        ports:
            - "8000:8000"
        depends_on:
            - rabbit
        entrypoint: "python -m neuron.server run-server -H 0.0.0.0 rabbitmq://rabbit:5672"

    parser-pose:
        <<: *neuron-service
        depends_on:
            - rabbit
        entrypoint: "python -m neuron.parsers run-parser pose rabbitmq://rabbit:5672"
    parser-feelings:
        <<: *neuron-service
        depends_on:
            - rabbit
        entrypoint: "python -m neuron.parsers run-parser feelings rabbitmq://rabbit:5672"
    parser-depth-image:
        <<: *neuron-service
        depends_on:
            - rabbit
        entrypoint: "python -m neuron.parsers run-parser depth_image rabbitmq://rabbit:5672"
    parser-color-image:
        <<: *neuron-service
        depends_on:
            - rabbit
        entrypoint: "python -m neuron.parsers run-parser color_image rabbitmq://rabbit:5672"

    saver:
        <<: *neuron-service
        depends_on:
            - rabbit
            - mongo
        entrypoint: "python -m neuron.saver run-saver mongodb://mongo:27017 rabbitmq://rabbit:5672"

    api:
        <<: *neuron-service
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        entrypoint: "python -m neuron.api run-server -H 0.0.0.0 -d mongodb://mongo:27017"

    gui:
        <<: *neuron-service
        ports:
            - "8080:8080"
        entrypoint: "python -m neuron.gui run-server -h 0.0.0.0 -H api"

volumes:
    raw:
    data:
